### ISSUE TITLE
Assalamualaikum 

### ISSUE THREAD

**Issue by Antroyz1** [Faishql/gloria-store#1]
Assalamualaikum mohon maaf mengganggu saya juga penonton WP Unpas setelah Pamer Project ingin mempelajari website anda kalau diperkenankan boleh minta database untuk gloria-store ini

**Comment by Faishql** [comment]
Waalaikumsalam, mohon maaf berhubung project ini belum sempurna jadi untuk source code nya tidak saya publikasikan dahulu.
